import "material-design-icons-iconfont/dist/material-design-icons.css";

import Vue from "vue";
import Vuetify, {
  VRow,
  VCol,
  VContent,
  VTextField,
  VCarousel,
  VTextarea,
  VCarouselItem,
  VTooltip,
  VCheckbox,
  VSelect,
  VIcon,
  VEditDialog,
  VApp,
  VExpansionPanels,
  VExpansionPanel,
  VExpansionPanelContent,
  VExpansionPanelHeader,
  VCard,
  VCardTitle,
  VExpandTransition,
  VCardText,
  VBtn,
  VSpacer,
  VDivider,
  VCardActions,
  VCardSubtitle,
  VContainer,
  VList,
  VListItemGroup,
  VListItem,
  VListItemContent,
  VListItemTitle,
  VListItemAction,
  VListItemSubtitle,
  VListItemIcon,
  VListGroup,
  VSnackbar,
  VDialog,
  VTimeline,
  VTimelineItem,
  VSpeedDial,
  VForm,
  VCombobox,
  VSwitch,
  VMenu,
  VListItemAvatar,
  VStepper,
  VStepperItems,
  VStepperHeader,
  VStepperStep,
  VStepperContent,
  VColorPicker,
  VFileInput,
  VAvatar,
  VAutocomplete,
  VTabs,
  VTab,
  VDataTable,
  VDataTableHeader,
  VDatePicker,
  VTabsSlider,
  VTabItem,
  VTabsItems,
  VTabTransition,
  VTabReverseTransition,
  VImg,
  VToolbar,
  VToolbarTitle,
  VRadioGroup,
  VRadio,
  VBtnToggle,
  VSheet,
  VCalendar,
  VTimePicker,
  VTimePickerClock,
  VTimePickerTitle,
  VChip,
  VChipGroup,
  VSubheader,
  VBadge,
  VSimpleCheckbox,
  VAppBar,
  VNavigationDrawer,
} from "vuetify/lib";
import pt from "vuetify/es5/locale/pt";
import { Ripple, Intersect, Touch, Resize } from "vuetify/lib/directives";

// import colors from 'vuetify/lib/util/colors'

Vue.use(Vuetify, {
  components: {
    VRow,
    VTooltip,
    VCol,
    VCarousel,
    VContent,
    VTextarea,
    VCarouselItem,
    VTextField,
    VCheckbox,
    VSelect,
    VIcon,
    VApp,
    VEditDialog,
    VExpansionPanels,
    VToolbar,
    VToolbarTitle,
    VExpansionPanel,
    VExpansionPanelContent,
    VExpansionPanelHeader,
    VCard,
    VCardTitle,
    VCardSubtitle,
    VCardActions,
    VExpandTransition,
    VCardText,
    VBtn,
    VSpacer,
    VDivider,
    VRadioGroup,
    VContainer,
    VList,
    VListGroup,
    VListItemGroup,
    VListItem,
    VListItemContent,
    VListItemTitle,
    VListItemAction,
    VListItemSubtitle,
    VListItemIcon,
    VSnackbar,
    VDialog,
    VTimeline,
    VTimelineItem,
    VSpeedDial,
    VForm,
    VCombobox,
    VSwitch,
    VMenu,
    VListItemAvatar,
    VStepper,
    VStepperItems,
    VStepperHeader,
    VStepperStep,
    VStepperContent,
    VColorPicker,
    VFileInput,
    VAvatar,
    VAutocomplete,
    VTab,
    VDataTable,
    VDataTableHeader,
    VDatePicker,
    VTabs,
    VTabsSlider,
    VTabItem,
    VTabsItems,
    VTabReverseTransition,
    VTabTransition,
    VSimpleCheckbox,
    VImg,
    VRadio,
    VBtnToggle,
    VSheet,
    VCalendar,
    VTimePicker,
    VTimePickerClock,
    VTimePickerTitle,
    VChip,
    VChipGroup,
    VSubheader,
    VBadge,
    VAppBar,
    VNavigationDrawer,
  },
  directives: { Ripple, Intersect, Touch, Resize },
});

export default new Vuetify({
  lang: {
    locales: {
      pt,
    },
    current: "pt",
  },
  icons: {
    iconfont: "mdi", // default - only for display purposes
  },
  options: {
    customProperties: true,
  },
});
